site_name: MkDocs woon17
repo_url: https://github.com/woon17/docs
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    # - navigation.footer
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      # pygments_lang_class: true
      line_spans: __span
      linenums: true
extra:
  social:
    - icon: material/github
      link: https://github.com/woon17
    - icon: material/linkedin
      link: https://www.linkedin.com/in/shufa-wen-7a530418b
  # timestamp: true
extra_javascript:
  - javascripts/open_in_new_tab.js
  - javascripts/highlight_selected_line_num.js
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - MkDocs:
      - mkDocs/admonitions.md
      - mkDocs/code-example.md
      - mkDocs/content-tabs.md
      - mkDocs/diagram-examples.md
  - Java:
      - java/test.md
  - FX:
      - fx/test.md
  - System Design:
      - system_design/test.md
  - Setup:
      - setup/python-vertual-env.md