site_name: MkDocs woon17
repo_url: https://github.com/woon17/docs
edit_uri: edit/main/docs/
plugins:
  # - Blog: plugins/blog.md
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    # - toc.integrate
    # - navigation.expand
    - navigation.top
    - content.action.edit
    - content.action.view
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      # pygments_lang_class: true
      line_spans: __span
      linenums: true
extra:
  social:
    - icon: material/github
      link: https://github.com/woon17
    - icon: material/linkedin
      link: https://www.linkedin.com/in/shufa-wen-7a530418b
  # timestamp: true
extra_javascript:
  - javascripts/open_in_new_tab.js
  - javascripts/highlight_selected_line_num.js
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - MkDocs:
      - mkDocs/admonitions.md
      - mkDocs/code-example.md
      - mkDocs/content-tabs.md
      - mkDocs/diagram-examples.md
  - Java:
      - Stack and heap: java/test.md
      - shutdown mecganism: java/shutdown.md
      - Thread:
        - java/thread/index.md
        - issue-visibility: java/thread/visibility.md
        - issue-atomicity: java/thread/atomicity.md
        - issue-ordering: java/thread/ordering.md
        - visibility and atomicity: java/volatile.md
        - multiple threads use case: 
          - 1. block task: java/thread/block-task.md
          - 2. CPU-Intensive Tasks: java/thread/CPU-Intensive-task.md
          - 3. Small, Fast Tasks (high vulume): java/thread/small-fast-task.md
  - FX:
      - fx/test.md
  - System Design: 
      - FR VS NFR: system_design/frAndNfre.md
      - IPC:
        - Summary: system_design/index.md
        - ipc: system_design/IPC/ipc.md
        - aeron mdc: system_design/IPC/aeron_mdc.md
  - Setup:
      - Python: 
        -  virEnv (mac): setup/python-vertual-env.md
      - SSH: 
        - github: setup/ssh-github.md
        - linux server: setup/ssh-server.md
  - Sprint Boot:
      - spring-boot/index.md
      - Multiple module maven: spring-boot/mmm.md
      - Maven: spring-boot/maven.md
  - Aeron:
    - Why aeron: aeron/adv.md
  - Linux:
    - cheatsheet: linux/cheatsheet.md
  - KDB:
    - kdb/index.md
    - setup on M3: kdb/setup.md
    - connect to kdb+ manually: kdb/connect.md
    - kx dashboard data source: kdb/kxDashboard.md
    - simple demo: kdb/demo.md
  - Blog:
    - blog/index.md
    - one url: blog/one-url.md